production:
  adapter: mysql2
  database: redmine
  host: db
  username: redmine
  password: redmine
  encoding: utf8

development:
  adapter: mysql2
  database: redmine 
  host: db
  username: redmine
  password: redmine
  encoding: utf8
