production:
  adapter: mysql2
  database: redmine
  host: mysql
  port: 3306
  username: redmine
  password: redmine
  encoding: utf8

development:
  adapter: mysql2
  database: redmine 
  host: mysql
  port: 3306
  username: redmine
  password: redmine
  encoding: utf8
